### ISSUE TITLE
Ingreso a la plataforma

### ISSUE THREAD

**Issue by javiesgm** [LumonColombia/pifs#2]
Al dar clic sobre el botón de ingreso desaparece la barra de navegación. Adicionalmente el footer de esta página es diferente a la página de inicio. 
![captura de pantalla 2017-12-22 a la s 8 43 21 a m](https://user-images.githubusercontent.com/14220404/34300152-cadecb5c-e6f4-11e7-8550-ca83aec9beaa.png)

**Comment by javiesgm** [comment]
PNG:
![captura de pantalla 2017-12-22 a la s 11 35 53 a m](https://user-images.githubusercontent.com/14220404/34305499-574a1738-e70c-11e7-860b-573a3d99a508.png) esto está uncluído en este mockup: 
https://drive.google.com/open?id=1VyFgPelbD4Sqv-8Ew-byHgR36YDusxPk

**Comment by johnfra797** [comment]
Solventado y publicado
