### ISSUE TITLE
Logo Gobierno

### ISSUE THREAD

**Issue by javiesgm** [LumonColombia/pifs#5]
png: 
![PIFFS-Ajustes-3.png](https://images.zenhubusercontent.com/56d4a9026caf56c9d38d0cdd/6586a039-2c55-42f5-b835-55c05e0fbba3)

Archivos logo: 
https://drive.google.com/open?id=1QtDQQ2Y82QPk8szVGJNcVrVZbmcDobIH

**Comment by johnfra797** [comment]
Solventado y publicado
